### ISSUE TITLE
Deprecated method when loading facts

### ISSUE THREAD

**Issue by minorOffense** [Sharpie/puppet-do_facts#1]
Get the following message when loading facts on a droplet

`/opt/puppetlabs/puppet/cache/lib/facter/digital_ocean.rb:30: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`

**Comment by minorOffense** [comment]
I’m no Ruby dev but this looks like it may be related. 

https://github.com/juliosueiras/vim-terraform-completion/issues/34#issuecomment-899452778

**Comment by minorOffense** [comment]
Should specify we’re using the latest puppet 6 agent/server on a centos 7 Droplet.

**Comment by Sharpie** [comment]
I think you're looking for https://github.com/jethrocarr/puppet-digitalocean. This module uses `Net::HTTP` instead of `URI.open` and does not have a `facter/digital_ocean.rb` file.
